<?php

namespace console\controllers;
use console\base\Controller;
use yii\helpers\Console;


/**
 * Class ConfigurationController
 * @package \console\controllers
 */
class ConfigurationController extends Controller
{
    public $migrationPath = [
        '@yz/migrations', '@yz/admin/migrations',
    ];

    public $cookieValidationKeyPath = [
        '@frontend/config/cookie.php',
        '@backend/config/cookie.php',
    ];

    public function actionInitial()
    {
        Console::output("Applying migrations...");

        foreach ($this->migrationPath as $path) {
            \Yii::$app->runAction('migrate', [
                'migrationPath' => $path
            ]);
        }

        if ($this->confirm("Generate cookieValidationKey?")) {
            foreach ($this->cookieValidationKeyPath as $path) {
                $key = \Yii::$app->security->generateRandomString(64);
                $file = \Yii::getAlias($path);
                $exported = var_export($key, true);
                $date = (new \DateTime('now'))->format('Y-m-d H:i:s');
                $msg =<<<PHP
<?php
// This file was automatically generated by 'configuration/initial script at {$date}
// It contains cookieValidationKey value
return {$exported};

PHP;
                file_put_contents($file, $msg);
                Console::output("Generated file ".$path);
            }
        }

        Console::output("All configuration is done!");
    }
} 