# Docker compose files to run applications

# Application code
app:
  image: ubuntu:14.04
  volumes:
    - .:/app

cli:
  image: yz2app/php:5.6-cli
  links:
    - db
  volumes_from:
    - app
  env_file:
    .env
  working_dir: '/app'


fpm:
  image: yz2app/php:5.6-fpm
  links:
    - db
  volumes_from:
    - app
  env_file:
    .env
  working_dir: '/app'


# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
frontend:
  image: yz2app/nginx:1.7
  links:
    - fpm
  volumes_from:
    - app
  ports:
    - "80"
    - "443"
  env_file:
     - .env
  environment:
      - SERVER_ROOT=/app/web/frontend
  command: "/root/run.sh"


# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
backend:
  image: yz2app/nginx:1.7
  links:
    - fpm
  volumes_from:
    - app
  ports:
    - "80"
    - "443"
  env_file:
    - .env
  environment:
    - SERVER_ROOT=/app/web/backend
  command: "/root/run.sh"


# Database volume
db:
  image: mysql:5.6
  ports:
    - "3306"
  env_file:
     - .env
  environment:
    - MYSQL_ROOT_PASSWORD=mysqlroot

